apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: runops-backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: runops.cl.us@geodis.com
  lifecycle: experimental
